FROM python:3.11-slim

WORKDIR /test

COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y chromium-driver chromium

COPY selenium_test.py .
CMD ["python", "selenium_test.py"]
